name: "Continuous Integration"

on:
    push:
        branches: continuous-integration-workflow

jobs:
    compute-stable-branches:
        name: Compute current and next stable release branches
        runs-on: ubuntu-latest

        steps:
            - name: Get current and next stable release branches
              id: get_branches
              run: |
                  curl \
                    -H "Accept: application/vnd.github.v3+json" \
                    -o latest.json \
                    "https://api.github.com/repos/${{ github.repository }}/releases/latest"
                  LATEST_STABLE_TAG=$(jq --raw-output '.tag_name' latest.json)
                  IFS='.' read LATEST_STABLE_MAJOR LATEST_STABLE_MINOR LATEST_STABLE_PATCH <<< "${LATEST_STABLE_TAG#v}"
                  echo "current_stable_branch=release/${LATEST_STABLE_MAJOR}.${LATEST_STABLE_MINOR}" >> $GITHUB_OUTPUT
                  if [[ ${LATEST_STABLE_MINOR} == "9" ]]; then
                    echo "next_stable_branch=release/$((LATEST_STABLE_MAJOR + 1)).0" >> $GITHUB_OUTPUT
                  else
                    echo "next_stable_branch=release/${LATEST_STABLE_MAJOR}.$((LATEST_STABLE_MINOR + 1))" >> $GITHUB_OUTPUT
                  fi
